### ISSUE TITLE
Error running tests with web workers

### ISSUE THREAD

**Issue by puranjayjain** [wlucha/angular-starter#13]
I used the following [command](https://angular.io/guide/web-worker) to add a webworker to the `app.component.ts`.

**Command**
`ng generate web-worker app`

I'm getting the following error below:

```
The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node12', or 'nodenext'.

    14   const worker = new Worker(new URL('./app.worker', import.meta.url));
```

Can you suggest a solution to this problem?

**Comment by wlucha** [comment]
@puranjayjain Please retry it with the latest updates + update @angular/cli globally.
Its working fine for me:
![image](https://user-images.githubusercontent.com/7531596/148525539-46330c94-c674-4d02-83e1-3a87fcf5c25c.png)

**Comment by puranjayjain** [comment]
Now try to test it directly, it will fail.

**Comment by wlucha** [comment]
@puranjayjain Which NodeJs version are you using?
https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3

I'm using v14.18.2.

**Comment by puranjayjain** [comment]
v16.13.1 and yarn 1.22.15
