### ISSUE TITLE
angular-starter doesnt work on StackBlitz

### ISSUE THREAD

**Issue by nereuseng** [wlucha/angular-starter#29]
Hi thanks for your work! Recently I try to checkout your project on StackBlitz, it doesnt work and stuck at `Compiling application & starting dev server…`

![image](https://github.com/wlucha/angular-starter/assets/11313394/b8dd2db4-ce92-4f3b-9f42-a76f654e80d2)

However when I checkout your repo locally, it seems work as expected. Not sure what is the cause and see if anyone has any workaround.

**Comment by spanic** [comment]
Hey @nereuseng check my Pull Request https://github.com/wlucha/angular-starter/pull/30, there's a workaround for that, hope that helps! 😉

**Comment by nereuseng** [comment]
@spanic Hi I tried your link of stackblitz, it stucks at installing dependencies:

![image](https://github.com/wlucha/angular-starter/assets/11313394/5bbda5fe-7a08-47b8-a473-d78c9b44039e)

**Comment by spanic** [comment]
@nereuseng I guess you just need to wait for some time... For me it also looks like it's getting stucked, but installation and startup continues after approx. 20 seconds. I suppose it depends on your machine's performance: I'm using MacBook Pro on M1 Pro, which is, actually, pretty fast, so if you're on Intel or something it will take more time.

Previously, before adding that StackBlitz config, for me it was also hanging on the same step that you reported, but now everything's fine. 

Could you please test it once again, just wait a little bit longer?

**Comment by wlucha** [comment]
Fixed with latest PR, thanks!

**Comment by nereuseng** [comment]
@spanic Tried again, it works now!

<img width="2195" alt="image" src="https://github.com/wlucha/angular-starter/assets/11313394/ed00a8a0-afc2-4718-8855-0518fa1aa4be">
